module.exports = {
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  PASSWORD_DOEST_NOT_MATCH: "PASSWORD_DOEST_NOT_MATCH",
};
